name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:5.12.0
        ports:
          - 7474:7474
          - 7687:7687
        options: "--env NEO4J_AUTH=neo4j/${{ secrets.NEO4J_PASSWORD }}"

    env:
      NEO4J_URI: bolt://localhost:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Install dependencies for ETL
        working-directory: ./etl
        run: go mod download

      - name: Install dependencies for API
        working-directory: ./api
        run: go mod download

      - name: Wait for Neo4j to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 7687 && break
            echo "Waiting for Neo4j..."
            sleep 2
          done

      - name: Run unit tests for ETL
        working-directory: ./etl
        run: go test -v ./...

      - name: Run unit tests for API
        working-directory: ./api
        run: go test -v ./...

      - name: Build ETL application
        working-directory: ./etl
        run: go build -v -o etl-app main.go

      - name: Build API application
        working-directory: ./api
        run: go build -v -o api-app main.go
